name: nodejs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install intelligo
        npm install intelligo-cli
        npm install uptime.js
        npm install neuro.js
        npm install @devmn/image-viewer
        npm install @devmn/stepper
        npm install @devmn/multi-select
      env:
        CI: true
